# Generated by Django 5.2.1 on 2025-08-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faxrecord',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faxrecord',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
